In [1]:
#coding: UTF-8

#ベクトル化手法
from gensim.models.doc2vec import Doc2Vec
from gensim.models.doc2vec import TaggedDocument
import numpy as np
import pandas as pd
import matplotlib.dates as mdates

f = open('tms_to_python_カメラ.txt','r')#空白で単語を区切り、改行で文書を区切っているテキストデータ

#txtファイルを配列に格納
trainings = []
for doc in f:
    trainings.append(doc)

In [2]:
import numpy as np
import MeCab
from sklearn.feature_extraction.text import CountVectorizer

#BoW実行
count = CountVectorizer()
bags = count.fit_transform(trainings)

#ベクトルをリストに格納
vectors_list = bags.toarray()

print(vectors_list)

features = count.get_feature_names()
print(features)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['α線', 'γ線', 'μｍ', 'あおり', 'あり', 'あわせ', 'いたずら', 'い質', 'うつ', 'うねり', 'おにぎり', 'おもり', 'お客様', 'お気に入り', 'お知らせ', 'かかと', 'かかり', 'かかわり', 'かがり', 'かご', 'かざし', 'かたち', 'かつ', 'かつ目', 'かぶり', 'かみそり', 'かみ合い', 'か所', 'がたつき', 'がん', 'きが', 'きっかけ', 'きび', 'きめ', 'きらめき', 'き裂', 'くし板', 'くぼみ', 'こて', 'こぶ', 'しきい', 'しま', 'しみ出し', 'しわ', 'すき入れ', 'すべり', 'すり', 'すれ違い', 'ずれ', 'せり出し', 'せん断', 'そのもの', 'そば', 'そり', 'たたみ', 'たばこ', 'たび', 'たむろ', 'たるみ', 'たわみ', 'だし', 'ちり', 'つぎ', 'つけ', 'つっぱり', 'つながり', 'つなぎ目', 'つぶり', 'つぶれ', 'つまみ', 'つや', 'とおり', 'とっさ', 'とも', 'なじみ', 'にじみ', 'ぬいぐるみ', 'ねじれ', 'ねじ込み', 'ねずみ', 'のこぎり', 'のぞき穴', 'はき心地', 'はず', 'はた', 'はみ出し', 'はり', 'はんだ', 'ばらつき', 'ばら積み', 'ひけ', 'ひこ', 'ひずみ', 'ひったくり', 'ひび割れ', 'びん', 'ふらつき', 'ほこり', 'ほつれ', 'ぼかし', 'ぼけ味', 'まとまり', 'まぶた', 'まわり', 'みぞ', 'めくり', 'めくれ', 'めっき', 'めまい', 'めんどう', 'もれ', 'やぶれ', 'やりとり', 'やり取り', 'やり直し', 'ゆがみ', 'ゆとり', 'ゆらぎ', 'ゆれ', 'ようす', 'よそ', 'よそ見', 'る報', 'ろう', 'ろう付け', 'ろ紙', '

In [ ]:
from gensim.models.doc2vec import Doc2Vec
from gensim.models.doc2vec import TaggedDocument
from sklearn.cluster import KMeans
import sys
from collections import defaultdict
import numpy as np
import matplotlib.pyplot as plt

#ドキュメント番号のリスト
doc_nums=range(1,1+len(trainings))

#クラスタリング設定
#クラスター数を変えたい場合はn_clustersを変えてください
n_clusters = 20
kmeans_model = KMeans(n_clusters=n_clusters, verbose=1, random_state=1, n_jobs=-1)

#クラスタリング実行
kmeans_model.fit(vectors_list)

#クラスタリングデータにラベル付け
labels=kmeans_model.labels_

#ラベルとドキュメント番号の辞書づくり
cluster_to_docs = defaultdict(list)
for cluster_id, doc_num in zip(labels, doc_nums):
    cluster_to_docs[cluster_id].append(doc_num)

#クラスター出力
for docs in cluster_to_docs.values():
    print(docs)

#x軸ラベル
x_label_name = []
for i in range(n_clusters):
    x_label_name.append("Cluster"+str(i))

#x=left ,y=heightデータ. ここではx=クラスター名、y=クラスター内の文書数
left = range(n_clusters)
height = []
for docs in cluster_to_docs.values():
    height.append(len(docs))
print(height,left,x_label_name)

#棒グラフ設定
plt.bar(left,height,color="#FF5B70",tick_label=x_label_name,align="center")
plt.title("Document clusters")
plt.xlabel("cluster name")
plt.ylabel("number of documents")
plt.grid(True)
plt.show()

In [ ]:
import os
import pandas as pd
from datetime import datetime as dt
from datetime import timedelta

#CSVファイルの読み込み
read_csv = pd.read_csv("カメラ_課題と解決手段.csv")

In [ ]:
#out_df
datelist = []
datalist = read_csv

#クラスター番号列を末尾に追加
datalist['a'] = labels

#TMS処理後の単語の列を末尾に追加
f = open('tms_to_python_カメラ.txt')

data1 = f.read()  #ファイル終端まで全て読んだデータを返す
f.close()
lines1 = data1.split('\n') #改行で区切る(改行文字そのものは戻り値のデータには含まれない)
datalist['b'] = lines1

#dfにCSVの情報を格納
df = datalist

#dfの中身を確認
print(df)

In [ ]:
#列名「クラスター番号」を追加
df.columns = ['No','特許No','出願番号','出願日','公開・公表番号','公開・公表日','登録番号','登録日','出願人・権利者名','発明の名称','要約','課題','解決手段','クラスター番号','TMS処理後の単語']

#不要な列を削除
df=df.drop(columns=['特許No','出願番号','出願日','公開・公表番号','公開・公表日','登録番号','登録日'])

#「No」列をindex番号として指定
df=df.set_index('No')

#dfの中身を確認
print(df)

In [ ]:
#out_df
datelist = []
datalist = df

#変更したCSV情報をファイルに出力
datalist.to_csv('BoW_カメラ.csv', encoding='utf_8_sig')