In [1]:
#coding: UTF-8

#ベクトル化手法
from gensim.models.doc2vec import Doc2Vec
from gensim.models.doc2vec import TaggedDocument
import numpy as np
import pandas as pd
import matplotlib.dates as mdates

f = open('tms_to_python_カメラ.txt','r')#空白で単語を区切り、改行で文書を区切っているテキストデータ

#txtファイルを配列に格納
trainings = []
for doc in f:
    trainings.append(doc)

In [2]:
import numpy as np
import MeCab
from sklearn.feature_extraction.text import TfidfVectorizer

#tf-idf計算
vectorizer = TfidfVectorizer()
tfidf = vectorizer.fit_transform(trainings)

#ベクトルをリストに格納
vectors_list = tfidf.toarray()

print(vectors_list)

features = vectorizer.get_feature_names()
print(features)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['α線', 'γ線', 'μｍ', 'あおり', 'あり', 'あわせ', 'いたずら', 'い質', 'うつ', 'うねり', 'おにぎり', 'おもり', 'お客様', 'お気に入り', 'お知らせ', 'かかと', 'かかり', 'かかわり', 'かがり', 'かご', 'かざし', 'かたち', 'かつ', 'かつ目', 'かぶり', 'かみそり', 'かみ合い', 'か所', 'がたつき', 'がん', 'きが', 'きっかけ', 'きび', 'きめ', 'きらめき', 'き裂', 'くし板', 'くぼみ', 'こて', 'こぶ', 'しきい', 'しま', 'しみ出し', 'しわ', 'すき入れ', 'すべり', 'すり', 'すれ違い', 'ずれ', 'せり出し', 'せん断', 'そのもの', 'そば', 'そり', 'たたみ', 'たばこ', 'たび', 'たむろ', 'たるみ', 'たわみ', 'だし', 'ちり', 'つぎ', 'つけ', 'つっぱり', 'つながり', 'つなぎ目', 'つぶり', 'つぶれ', 'つまみ', 'つや', 'とおり', 'とっさ', 'とも', 'なじみ', 'にじみ', 'ぬいぐるみ', 'ねじれ', 'ねじ込み', 'ねずみ', 'のこぎり', 'のぞき穴', 'はき心地', 'はず', 'はた', 'はみ出し', 'はり', 'はんだ', 'ばらつき', 'ばら積み', 'ひけ', 'ひこ', 'ひずみ', 'ひったくり', 'ひび割れ', 'びん', 'ふらつき', 'ほこり', 'ほつれ', 'ぼかし', 'ぼけ味', 'まとまり', 'まぶた', 'まわり', 'みぞ', 'めくり', 'めくれ', 'めっき', 'めまい', 'めんどう', 'もれ', 'やぶれ', 'やりとり', 'やり取り', 'やり直し', 'ゆがみ', 'ゆとり', 'ゆらぎ', 'ゆれ', 'ようす', 'よそ'

In [3]:
from gensim.models.doc2vec import Doc2Vec
from gensim.models.doc2vec import TaggedDocument
from sklearn.cluster import KMeans
import sys
from collections import defaultdict
import numpy as np
import matplotlib.pyplot as plt

#ドキュメント番号のリスト
doc_nums=range(1,1+len(trainings))

#クラスタリング設定
#クラスター数を変えたい場合はn_clustersを変えてください
n_clusters = 20
kmeans_model = KMeans(n_clusters=n_clusters, verbose=1, random_state=1, n_jobs=-1)

#クラスタリング実行
kmeans_model.fit(vectors_list)

#クラスタリングデータにラベル付け
labels=kmeans_model.labels_

#ラベルとドキュメント番号の辞書づくり
cluster_to_docs = defaultdict(list)
for cluster_id, doc_num in zip(labels, doc_nums):
    cluster_to_docs[cluster_id].append(doc_num)

#クラスター出力
for docs in cluster_to_docs.values():
    print(docs)

#x軸ラベル
x_label_name = []
for i in range(n_clusters):
    x_label_name.append("Cluster"+str(i))

#x=left ,y=heightデータ. ここではx=クラスター名、y=クラスター内の文書数
left = range(n_clusters)
height = []
for docs in cluster_to_docs.values():
    height.append(len(docs))
print(height,left,x_label_name)

#棒グラフ設定
plt.bar(left,height,color="#FF5B70",tick_label=x_label_name,align="center")
plt.title("Document clusters")
plt.xlabel("cluster name")
plt.ylabel("number of documents")
plt.grid(True)
plt.show()

[1, 11, 26, 34, 48, 49, 60, 72, 82, 83, 91, 101, 104, 106, 151, 155, 231, 458, 471, 483, 531, 666, 698, 704, 723, 842, 848, 914, 934, 942, 947, 1011, 1034, 1036, 1054, 1056, 1070, 1071, 1115, 1130, 1183, 1187, 1256, 1271, 1364, 1382, 1461, 1492, 1522, 1528, 1534, 1591, 1622, 1629, 1654, 1655, 1672, 1694, 1791, 1796, 1832, 1872, 1901, 1915, 1933, 1934, 1935, 1991, 2008, 2022, 2043, 2044, 2045, 2046, 2057, 2098, 2132, 2142, 2166, 2215, 2216, 2228, 2274, 2335, 2345, 2374, 2411, 2422, 2459, 2596, 2657, 2683, 2705, 2706, 2741, 2772, 2834, 2850, 2904, 2928, 2989, 3093, 3112, 3157, 3186, 3246, 3290, 3291, 3292, 3295, 3296, 3297, 3302, 3345, 3347, 3409, 3443, 3535, 3582, 3612, 3620, 3622, 3680, 3726, 3732, 3750, 3777, 3789, 3832, 3884, 3897, 3945, 4083, 4106, 4110, 4127, 4187, 4237, 4257, 4319, 4358, 4411, 4412, 4441, 4501, 4502, 4520, 4547, 4568, 4633, 4635, 4748, 4775, 4788, 4807, 4894, 4941, 4945, 4988, 5037, 5084, 5085, 5126, 5151, 5162, 5211, 5212, 5250, 5267, 5303, 5309, 5360, 5380, 5381

<Figure size 640x480 with 1 Axes>

In [4]:
import os
import pandas as pd
from datetime import datetime as dt
from datetime import timedelta

#CSVファイルの読み込み
read_csv = pd.read_csv("カメラ_課題と解決手段.csv")

In [5]:
#out_df
datelist = []
datalist = read_csv

#クラスター番号列を末尾に追加
datalist['a'] = labels

#TMS処理後の単語の列を末尾に追加
f = open('tms_to_python_カメラ.txt')

data1 = f.read()  #ファイル終端まで全て読んだデータを返す
f.close()
lines1 = data1.split('\n') #改行で区切る(改行文字そのものは戻り値のデータには含まれない)
datalist['b'] = lines1

#dfにCSVの情報を格納
df = datalist

#dfの中身を確認
print(df)

       Unnamed: 0     No         出願番号         出願日        公開・公表番号      公開・公表日  \
0               0     37          NaN  2019-02-07  WO2019/163545  2019-08-29   
1               1     38          NaN  2019-02-07  WO2019/163544  2019-08-29   
2               2     39          NaN  2019-02-07  WO2019/163543  2019-08-29   
3               3     40          NaN  2019-02-07  WO2019/163542  2019-08-29   
4               4     52          NaN  2018-02-26  WO2019/163118  2019-08-29   
...           ...    ...          ...         ...            ...         ...   
28458       28458  35253  特願平11-85221  1999-03-29  特開2000-278585  2000-10-06   
28459       28459  35254  特願平11-80595  1999-03-24  特開2000-278612  2000-10-06   
28460       28460  35255  特願平11-72893  1999-03-18  特開2000-266523  2000-09-29   
28461       28461  35256  特願平11-50212  1999-02-26  特開2000-253285  2000-09-14   
28462       28462  35257  特願平11-17504  1999-01-26  特開2000-215398  2000-08-04   

              登録番号         登録日         

In [6]:
#列名「クラスター番号」を追加
df.columns = ['No','特許No','出願番号','出願日','公開・公表番号','公開・公表日','登録番号','登録日','出願人・権利者名','発明の名称','要約','課題','解決手段','クラスター番号','TMS処理後の単語']

#不要な列を削除
df=df.drop(columns=['特許No','出願番号','出願日','公開・公表番号','公開・公表日','登録番号','登録日'])

#「No」列をindex番号として指定
df=df.set_index('No')

#dfの中身を確認
print(df)

                             出願人・権利者名                       発明の名称  \
No                                                                  
0      パナソニックＩＰマネジメント株式会社,堀尾　和幸,池崎　一生        オペレータ端末及びキャリブレーション方法   
1      パナソニックＩＰマネジメント株式会社,堀尾　和幸,池崎　一生        双方向映像通信システム及びオペレータ端末   
2       パナソニックＩＰマネジメント株式会社,平澤　園子,藤松　健         執務席提示システムおよび執務席提示方法   
3       パナソニックＩＰマネジメント株式会社,平澤　園子,藤松　健       滞在状況表示システムおよび滞在状況表示方法   
4                     株式会社オプティム,菅谷　俊二  コンピュータシステム、ドローン制御方法及びプログラム   
...                               ...                         ...   
28458                      ブラザー工業株式会社          デジタルカメラのネットワークシステム   
28459                      カシオ計算機株式会社   撮像装置及び撮像装置のメカシャッタ応答遅れ測定方法   
28460                        ＪＵＫＩ株式会社             被測定物の測定方法及びその装置   
28461                        キヤノン株式会社                        電子機器   
28462                         マツダ株式会社                 車両の周囲情報報知装置   

                                                      要約  \
No                                        

In [7]:
#out_df
datelist = []
datalist = df

#変更したCSV情報をファイルに出力
datalist.to_csv('tf-idf_カメラ.csv', encoding='utf_8_sig')